all:
	@(cd volume.ext && $(MAKE))
	@(cd ps2.ext && $(MAKE))
	@(cd ide.ext && $(MAKE))
	@(cd fsl.ext && $(MAKE))

clean:
	@(cd volume.ext && $(MAKE) clean)
	@(cd ps2.ext && $(MAKE) clean)
	@(cd ide.ext && $(MAKE) clean)
	@(cd fsl.ext && $(MAKE) clean)
